### ISSUE TITLE
Pomodoro Mini App

### ISSUE THREAD

**Issue by Lordhacker756** [Lordhacker756/open-dashboard#5]
# A new feature that I'm trying to implement is a Pomodoro app. 
## Concept
* There's a button beside the clock that lets users select the duration for Pomodoro viz 25min, 35min, and 45min. 
* After selecting the time, we can have a countdown like [Flip Clock](https://www.flipclock.us/)
* When the Pomodoro is done, play a sound to notify the user
* We can also show the time remaining at the page title for the convenience of the user

** New suggestions are welcome. Let's see what we can build together 🤝🏻**

**Comment by jonaaldas** [comment]
I am working on this one! :)

**Comment by Lordhacker756** [comment]
Best of luck!😄

**Comment by jonaaldas** [comment]
Hi, I submitted a pull request.

**Comment by Lordhacker756** [comment]
The basic pomodoro app is ready. However further improvements will be on a separate issue
