### ISSUE TITLE
Icon not being rendered in extension

### ISSUE THREAD

**Issue by Lordhacker756** [Lordhacker756/open-dashboard#6]
The icon of the weather is fetched but not getting rendered and also the aspect ratio is also getting distorted when installing the build as an extension.

**Comment by jonaaldas** [comment]
![Screen Shot 2022-06-07 at 8 14 38 PM](https://user-images.githubusercontent.com/12662909/172510397-b6a9c6a1-45d7-46f3-9784-206662db9cea.png)
Do you mean this icon?

**Comment by Lordhacker756** [comment]
Yes, when the build is installed as an extension, the icon doesn't render itself

<img width="157" alt="image" src="https://user-images.githubusercontent.com/70888328/172511851-5e07e227-0cec-4596-a298-82aa8e90e9d1.png">

Despite being fetched
